[2024-06-03T07:56:27.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-03T07:56:27.133+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.tsk_send_file_to_s3 manual__2024-06-03T07:56:02.644497+00:00 [queued]>
[2024-06-03T07:56:27.139+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.tsk_send_file_to_s3 manual__2024-06-03T07:56:02.644497+00:00 [queued]>
[2024-06-03T07:56:27.139+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-06-03T07:56:27.156+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): tsk_send_file_to_s3> on 2024-06-03 07:56:02.644497+00:00
[2024-06-03T07:56:27.160+0000] {standard_task_runner.py:63} INFO - Started process 4952 to run task
[2024-06-03T07:56:27.163+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'my_first_dag', 'tsk_send_file_to_s3', 'manual__2024-06-03T07:56:02.644497+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/myfirstdag.py', '--cfg-path', '/tmp/tmp90c9gwml']
[2024-06-03T07:56:27.165+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask tsk_send_file_to_s3
[2024-06-03T07:56:27.203+0000] {task_command.py:426} INFO - Running <TaskInstance: my_first_dag.tsk_send_file_to_s3 manual__2024-06-03T07:56:02.644497+00:00 [running]> on host ip-172-31-35-145.ap-southeast-1.compute.internal
[2024-06-03T07:56:27.274+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='jeqiu' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='tsk_send_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-03T07:56:02.644497+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-03T07:56:02.644497+00:00'
[2024-06-03T07:56:27.275+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-03T07:56:27.288+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-03T07:56:27.289+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'aws s3 mv /home/ubuntu/response_data_03062024075605.json s3://jqiu-landing-zone-first-dag-project']
[2024-06-03T07:56:27.296+0000] {subprocess.py:86} INFO - Output:
[2024-06-03T07:56:27.831+0000] {subprocess.py:93} INFO - move failed: ../../home/ubuntu/response_data_03062024075605.json to s3://jqiu-landing-zone-first-dag-project/response_data_03062024075605.json Unable to locate credentials
[2024-06-03T07:56:27.909+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-03T07:56:27.910+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-03T07:56:27.920+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/e2e_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/e2e_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/e2e_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/e2e_venv/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-03T07:56:27.923+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=tsk_send_file_to_s3, run_id=manual__2024-06-03T07:56:02.644497+00:00, execution_date=20240603T075602, start_date=20240603T075627, end_date=20240603T075627
[2024-06-03T07:56:27.938+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task tsk_send_file_to_s3 (Bash command failed. The command returned a non-zero exit code 1.; 4952)
[2024-06-03T07:56:27.978+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-03T07:56:27.990+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-03T07:56:27.990+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
